services:
  xbox-dvr:
    container_name: 'xbox-dvr'
    hostname: 'xbox-dvr'
    image: 'wolveix/xbox-dvr:latest'
    volumes:
      - '/your/output/directory:/out'
    environment:
      - apiKey=your-openxbl-api-key
      - autoDelete=false
      - savePath=/out
    restart: no