name: Build
on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22.0'
      - run: |
          cd cmd/xdvr
          go build -o xdvr